version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/python:1-3.11
    volumes:
      - ..:/workspace
    network_mode: service:mongodb

  mongodb:
    image: mongo:6.0
    restart: always
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb_data: